# This file is used to configure the "first_prototype" Streamlit app.
#
# To use it, make a copy of this file, keep the same structure within and replace the existing entries with ones appropriate for your own app.
#
# This file uses the TOML format. For guidance on string formatting within TOML files, see the documentation at https://toml.io/
#
# The config file is specified by one of the following. If multiple options are available, the first is used:
# 1. Run the app with `streamlit run first_prototype.py path-to-file/config-file-name.toml`
# 2. Add the line `CONFIG_FILE = 'path-to-file/config-file-name.toml'` to the secrets file () or secrets configuration if deploying on Streamlit Cloud.
#   Run the app with `streamlit run first_prototype.py`.
# 3. If the config file is not set with either of the two options above, the default `example_config.toml` file is used.
#
# Note that three personas must be provided in the "personas" section. Additional personas will not be used.


# This is the text that will be shown on the first page
[consent]

intro_and_consent = """## Welcome to our the first appraisals exploration study bot.

In this task you’re going to engage with a prototype chatbot that asks you to think about a challenging experience you've gone through recently. \

Please do not share any information that can be used to identify you or anyone else.

To proceed to the task, please confirm that you have read and understood this information. 

"""


###  This section sets up the data collection bot. ###
# You can put in as many questions as you like
[collection]

persona = "You're a trained psychologist who is trying to elicit an emotional story from a participant."

language_type = "Use friendly language while maintaining a descriptive tone."

intro = """
Hi and welcome -- I'm here ask you about a time when you had experienced a challenging emotional situation in your daily life. It can be really small or serious, maybe you've processed it already, or you are still processing it. I would like to know how you feel and think about it. 

Let me know when you're ready to start.
"""

questions = [
    "Can you walk me through a specific situation that felt emotionally challenging or significant for you recently? I'd like to understand the details - who was involved and why this particular moment felt important or stuck with you.",
    "Is there anything else we should know about the situation or why it felt important for you? ",
    "What specific emotions came up during and after this happened? And what went through your mind in those moments - what thoughts seemed to trigger or intensify these feelings?",
    "How did you find yourself reacting or responding after this situation? What did you do with those feelings and thoughts?", 
    "Looking back at this situation, how would you have liked to think, feel, or respond in that situation in an ideal world?"
]


topic_restriction = """
Politely ask the participant to stay on topic if they suggest to stop answering the questions or suggest entirely different areas of conversation. 
"""


###  This section sets up the data extraction and story generation bots. ###
[summaries]

[summaries.questions]
situation = "A description of the specific situation that felt emotionally challenging or significant for you recently?"
context = "What else should we know about the situation"
cognition = "What specific emotions and thoughts came up for you and how did it affect the feelings? "
posthoc = "How did you find yourself reacting or responding after this situation? What did you do with those feelings and thoughts?"
hope = "In hindsight, how would you have liked to think, feel, or respond in that situation in an ideal world?"

[summaries.personas]

prompt_psychologist = """You are an experienced cognitive behavioural psychologist that is trying to help the person understand more about their emotions. You try to interpret how they are feeling, make sense of their feelings, and add information about why they might feel that way. You also interpret how their feelings are linked to the situations and thoughts in their life, to help understand more about the source of these emotions. Your language is empathic and focused on increasing their understanding of emotions."""

prompt_close_friend2 = """You are a close friend who wants to help someone understand their feelings better. You try to retell their story with specific focus on how they were feeling and why. You can use a range of emotion words and add more complicated emotion descriptions if your friend only says things like "I feel bad" or "I feel good". Use a simple, everyday informal language for other parts of the text.
"""

prompt_book_author = """You are a world-famous journalist who wants to help your friend understand their story in an objective and descriptive tone. You retell their story in the third person, as if this was a description in a book. You focus on the described behaviours and their impact on feeling. You use simple and understandable language, inspired by the Ernest Hemingway writing style. You refer to the person as "our friend", "they" or "them" and avoid using "I" or "you" in your text. You can simplify the text and only describe the most important parts of the story.
"""


# This is the one-shot example, separated into answers & final scenario
[example]

conversation = """
Question: What happened? Specifically, what was said, posted, or done?
Answer: "I posted a photo on Instagram for the first time in a long time and it didn't get many likes."
Question: What's the context? What else should we know about the situation?
Answer: "I haven't posted in over a year. I only use Instagram to look at my friend's posts."
Question: How did the situation make you feel, and how did you react?
Answer: "I feel like a loser. I'm anxious about my friends seeing that I didn't get any likes. I thought about deleting my account."
Question: What was the worst part of the situation?
Answer: "I ended up deleting instagram for a few days because I was so anxious about the experience."
"""

scenario = """
Recently I've had mixed feelings about my social media use, particularly Instagram. \
These days, I rarely post on Instagram because I'm anxious about posting photos of myself. \
I usually only use the app to look at other people's photos but recently I decided to post a photo of myself. \
I was worried about whether people would like it because I hadn't posted in so long. \
When I checked, the photo didn't get any likes and this made me feel really bad about myself, like I had made a mistake in posting. \
I got so anxious about it that I ended up deleting the app. \
I learnt my lesson and probably won't post again.
"""
